export default {
    REQUEST_MENU_LIST: 'REQUEST_MENU_LIST',
    SUCCESS_MENU_LIST: 'SUCCESS_MENU_LIST',
    ERROR_MENU_LIST: 'ERROR_MENU_LIST',
    SAVE_FORM_DATA: 'SAVE_FORM_DATA',
    CLEAR_FORM_DATA: 'CLEAR_FORM_DATA'
}